id: P005505
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17605
  title: ས་སྐྱ་པའི་གསུང་རབ་དཔེ་རྙིང་ཁག་གཅིག་ཕྱོགས་བསྒྲིགས་པར་དུ་བསྐྲུན་པའི་དཀར་ཆག་རིན་ཆེན་མཛོད་བརྒྱ་འབྱེད་པའི་ལྡེ་མིག
  author: ''
  volumes: {}
