id: P005505
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:55:19.653958
source_metadata:
  id: bdr:W1KG17605
  title: ས་སྐྱ་པའི་གསུང་རབ་དཔེ་རྙིང་ཁག་གཅིག་ཕྱོགས་བསྒྲིགས་པར་དུ་བསྐྲུན་པའི་དཀར་ཆག་རིན་ཆེན་མཛོད་བརྒྱ་འབྱེད་པའི་ལྡེ་མིག
  author: ''
  volumes:
    e1b18596a9b24241b2e5f3b3317af02a:
      image_group_id: I1KG17918
      title: ''
      volume_number: 1
      total_pages: 186
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
