id: I972624CB
legacy_id: P005505
ocr_import_info:
  bdrc_scan_id: W1KG17605
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T07:19:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:29:39.014756+00:00'
last_modified: 2022-08-27 14:29:56.892155
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17605
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17605
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ས་སྐྱ་པའི་གསུང་རབ་དཔེ་རྙིང་ཁག་གཅིག་ཕྱོགས་བསྒྲིགས་པར་དུ་བསྐྲུན་པའི་དཀར་ཆག་རིན་ཆེན་མཛོད་བརྒྱ་འབྱེད་པའི་ལྡེ་མིག
  author: འཇམ་དབྱངས་ཀུན་དགའ
statistics:
  ocr_word_mean_confidence_index: 0.911378373172909
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG17918:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17918
      total_pages: 186
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17918.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.911378373172909
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
