id: I972624CB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:19:44+00:00'
last_modified: '2022-06-08T03:33:50.741446+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17605
  title: ས་སྐྱ་པའི་གསུང་རབ་དཔེ་རྙིང་ཁག་གཅིག་ཕྱོགས་བསྒྲིགས་པར་དུ་བསྐྲུན་པའི་དཀར་ཆག་རིན་ཆེན་མཛོད་བརྒྱ་འབྱེད་པའི་ལྡེ་མིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8FC4:
      image_group_id: I1KG17918
      title: ''
      total_pages: 186
      order: 1
      base_file: 8FC4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
